#/bin/bash

NODE_ENV=production \
APP_DB_URL=$MONGODB_URLS_APP \
APP_DB_OPLOG_URL=$MONGODB_URLS_APP_OPLOG \
KADIRA_API_URL=$API_BASE_URL/core \
MAIL_URL=$ALERTSMAN_MAIL_URL \
TICK_TRIGGER_INTERVAL=60000 \
LIBRATO_METRICS_PREFIX=alertsman. \
LIBRATO_EMAIL=$ALERTSMAN_LIBRATO_USER \
LIBRATO_TOKEN=$ALERTSMAN_LIBRATO_KEY \
GOOGLE_DEV_KEY=$ALERTSMAN_GOOGLE_DEV_KEY \
DEBUG=alertsman:messenger \
  node server.js
