#/bin/bash

MONGO_APP_URL=$MONGODB_URLS_APP \
MONGO_SHARD_URL_one=$MONGODB_URLS_SHARD_ONE \
MONGO_SHARD_URL_two=$MONGODB_URLS_SHARD_TWO \
MONGO_SHARD_URL_three=$MONGODB_URLS_SHARD_THREE \
MAIL_URL=$API_MAIL_URL \
JWT_SECRET="secret" \
JWT_LIFETIME="1d" \
AUTH_SECRET="secret" \
PORT=7007 \
NODE_ENV=production \
  node_modules/.bin/nodemon server.js
