heroku config:set \
  MONGODB_URLS_APP=$MONGODB_URLS_APP \
  MONGODB_URLS_APP_OPLOG=$MONGODB_URLS_APP_OPLOG \
  API_BASE_URL=$API_BASE_URL \
  ALERTSMAN_MAIL_URL=$ALERTSMAN_MAIL_URL\
  ALERTSMAN_LIBRATO_USER=$ALERTSMAN_LIBRATO_USER \
  ALERTSMAN_LIBRATO_KEY=$ALERTSMAN_LIBRATO_KEY \
  ALERTSMAN_GOOGLE_DEV_KEY=$ALERTSMAN_GOOGLE_DEV_KEY
